ECHO    off

d:\utilitys\batch\command /c tpc batch_   crt_     fcb_     fenster_ handle_  handle1_ lognam_  lognamo_
d:\utilitys\batch\command /c tpc mount1_  mount_   syshalt_ syslog_  wahl_    istr_    path_    lognam1_
d:\utilitys\batch\command /c tpc environ_ editz_   nim_     n_men_
d:\utilitys\batch\command /c tpc cadlist_ baudat_

        copy *.tpu ..                                    > NUL
        del  *.tpu                                       > NUL
