ECHO    off
d:\utilitys\batch\command /c tpc mbat1    bbatch   ebatch   dbatch   tbatch
d:\utilitys\batch\command /c tpc tbat1    tbat2    tbat3    cdir     crc
d:\utilitys\batch\command /c tpc rbatch   ubatch   ibh1     ibh2     ibh3
d:\utilitys\batch\command /c tpc ibatch   amt      clock    create_b change_b
d:\utilitys\batch\command /c tpc c-nam    c-menu
d:\utilitys\batch\command /c tpc e-nam    e-menu   e-pass   e-path
